### ISSUE TITLE
Support for std::string

### ISSUE THREAD

**Issue by dmchell** [frida/frida-gum#11]
Support for string objects would be mighty useful.

Possible naming convention of Memory.readStdString() ?

**Comment by oleavr** [comment]
Great idea! Let's get this into the upcoming release.

**Comment by dmchell** [comment]
For reference, this sort of works...

var ptrToStr = <-- your ptr to std::string object
var cstrptr = Module.findExportByName("libstdc++.6.dylib", "_ZNKSs5c_strEv");
var cstr = new NativeFunction(cstrptr,'pointer',['pointer']);
var str = Memory.readUtf8String(cstr(ptrToStr));

**Comment by oleavr** [comment]
This belongs in user-space modules in npm.

**Comment by iddoeldor** [comment]
any updates ? read&write std::string would be very helpful
