### ISSUE TITLE
Android 5.0.1 ART: app crash when calling certain functions from frida hook

### ISSUE THREAD

**Issue by stevielavern** [frida/frida-gum#113]
Hi,

I recently switched from Android 4 to 5.0.1, so in the same time from Dalvik to ART.
Now I'm experiencing some crashes when calling "some functions" from a frida hook that worked just fine with Dalvik. I'm sorry for the approximate description, but I didn't manage to identify which function exactly provoque the crashes.

For instance, in a hook of a method taking a ByteBuffer as only param:

```
function hook(bbparam) { ... }
Java.use(aclass).amethod.overload("java.nio.ByteBuffer").implementation = hook;
```

I can call some methods without provoking a crash, like the duplicate method:

```
var dup = bbparam.duplicate.call(bbparam); // works fine
```

But not others, like all the different get() methods, or the array() method:

```
var arr = bbparam.array.call(bbparam); //crash
var bytes = bbparam.get.overload("int").call(bbparam); //crash
```

The backtrace I observe in logcat is the following:

```
backtrace:
    /system/lib/libart.so (art::mirror::ArtMethod::ToDexPc(unsigned int, bool)+175)
    /system/lib/libart.so (art::BuildInternalStackTraceVisitor<false>::VisitFrame()+180)
    /system/lib/libart.so (art::StackVisitor::WalkStack(bool)+272)
    /system/lib/libart.so (_jobject* art::Thread::CreateInternalStackTrace<false>(art::ScopedObjectAccessAlreadyRunnable const&) const+324)
    /system/lib/libart.so (art::Throwable_nativeFillInStackTrace(_JNIEnv*, _jclass*)+22)
    /data/dalvik-cache/arm/system@framework@boot.oat
```

Are there currently similar known issues in android 5.0.1 with ART ?
Thanks.

**Comment by oleavr** [comment]
Thanks for reporting. This is unfortunately a known issue, as the ART support isn't finished yet. Curiously I also ran into `art::mirror::ArtMethod::ToDexPc()` failing, but didn't have time to figure out why. If you get a chance to study the ART source code to get to the bottom of this, that would be awesome!

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
