### ISSUE TITLE
Add File.read api

### ISSUE THREAD

**Issue by radare** [frida/frida-gum#115]
Currently, the `File` API of the agent is write-only. It would be good to have proper support for seek and read too. But for 99% of the cases the use would be like:

* dump `fs.writeFileSync()`
* slurp `fs.readFileSync()`
* append `fs.appendFileSync()`
* truncate

**Comment by radare** [comment]
This can be implemented in CommonJS in a separate module available via npm (`frida-file` maybe?)

**Comment by oleavr** [comment]
Yep I think that's a great idea. The long-term goal should be to have as little as possible in the core, and have a community of modules that add useful APIs by building on the low-level primitives. It would for example be neat if the `Java`/`ObjC` APIs were moved out into modules that could be updated more frequently than Frida itself, also making it easier for the community to fork these parts and experiment with new ideas.

**Comment by oleavr** [comment]
This issue is now solved by [frida-fs](https://github.com/nowsecure/frida-fs).
