### ISSUE TITLE
Confusing/non-consistent type representation in overload(...)

### ISSUE THREAD

**Issue by stevielavern** [frida/frida-gum#117]
When using `Java.method.overload(...)`, the full name of native types must be used and not the letters representing these types in Java signatures. For instance `int` instead of `I`, `byte` instead of `B`, etc.

But when the parameter is an array of a native type, the letter must be used and not the full name.
For instance, if the method is `method(int x, int y[])`, overload must be used like this: `method.overload("int", "[I")` and not with `[int` or`int[]`.

While not a big issue, this can be misleading/counter-intuitive.
A simpler way to avoid any confusion could be to use the signature of the method in `overload()`, for instance for the previous example `I[I`.

**Comment by oleavr** [comment]
Very good point! /cc @marc1006

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-java#4.
