### ISSUE TITLE
Stalker does not work on Android

### ISSUE THREAD

**Issue by stevielavern** [frida/frida-gum#118]
The following script does not produce any output on Android:
It is executed with `frida -U -l stalker-test.js com.android.contacts`

```
Stalker.follow({
    events: {
        call: true,
        ret: true,
        exec: true
    },
    onReceive: function (events) {
        console.log("onReceive");
    },
    onCallSummary: function (summary) {
        console.log("onCallSummary");
    }
});
```

**Comment by oleavr** [comment]
Hi,

Stalker is x86-only for now, and the ARM and ARM64 implementations are just stubs:
https://github.com/frida/frida-gum/blob/b1c2864e665d9c13f7e13211c5e5b74c7b92206b/gum/backend-arm/gumstalker-arm.c#L107
https://github.com/frida/frida-gum/blob/b1c2864e665d9c13f7e13211c5e5b74c7b92206b/gum/backend-arm64/gumstalker-arm64.c#L106

The x86 implementation can be found here:
https://github.com/frida/frida-gum/blob/master/gum/backend-x86/gumstalker-x86.c

I'm hoping that someone might be interested in helping out with porting it at some point. :-)

Cheers!

**Comment by stevielavern** [comment]
Oh ok, thanks for the clarification!
It could be useful to add this information in the documentation (http://www.frida.re/docs/javascript-api/#stalker)

**Comment by nevermoe** [comment]
Sorry, are ARM and ARM64 implementations still stubs now?
