### ISSUE TITLE
frida-server crashing while doing memory dump

### ISSUE THREAD

**Issue by Nightbringer21** [frida/frida-gum#121]
Hi,

I am trying to use Frida as a memory dumper of an iOS application. My problem is that when the size of the memory chunk is too big (in my case over 40MB), the frida-server is crashing. The second issue that I noticed is that even thought I have defined to read only address spaces where the application has read and write access, I always get one or two Memory access violation errors. A chunk of the code I have used is the following:

    Memories = session.enumerate_ranges('rw-')
    for memory in Memories:
            base = memory.base_address
            size = memory.size            	
            dump =  session.read_bytes(base, size)
            f = open(directory+'\\'+str(hex(base))+'_dump.data', 'wb')            
            f.write(dump)
            f.close

**Comment by oleavr** [comment]
Very interesting. Thanks for reporting, will investigate.

**Comment by oleavr** [comment]
This is actually a bug in frida-python, as `read_bytes()` should be smarter and do proper flow control, for example by using [frida-remote-stream](https://github.com/nowsecure/frida-remote-stream) together with [frida-memory-stream](https://github.com/nowsecure/frida-memory-stream).
