### ISSUE TITLE
Interceptor.attach() onLeave at wrong address

### ISSUE THREAD

**Issue by mrmacete** [frida/frida-gum#126]
I'm using Interceptor.attach on an arm64 objc ios binary, and onLeave is not called at the right place. How is the "end" of the method detected on an arch like arm64 where it is far from obvious? is it possible to define the "leave point" manually for a method ?

**Comment by mrmacete** [comment]
nevermind, it was a failure of mine, the leave point is correct.

**Comment by mrmacete** [comment]
no, sorry, it is a correct leave point but of an unrelated method

**Comment by oleavr** [comment]
Did you get to the bottom of it? Note that looking at the call stack in a debugger will be confusing as Interceptor replaces the return address (in `LR` in arm64) while the call is in progress, and restores it afterwards (it maintains a per-thread stack).

**Comment by mrmacete** [comment]
actually what i did is:
+ reading this.context.pc in the onLeave callback
+ adding current ASLR offset
+ go in r2 or hopper at that offset
+ getting the address of the epilogue of a method completely unrelated to the attached one

**Comment by oleavr** [comment]
Aha. That should be the return address according to this (with the wrong address there it will crash pretty fast):
https://github.com/frida/frida-gum/blob/master/gum/guminterceptor.c#L986
Maybe the ASLR offset is applied wrong?
