### ISSUE TITLE
Be able to get/set all registers not only PC,SP

### ISSUE THREAD

**Issue by radare** [frida/frida-gum#13]

**Comment by oleavr** [comment]
Which API is this?

**Comment by oleavr** [comment]
I think this was fixed recently in 54cf174a2631bd430b94cb2431b8927ae2a59b29.

**Comment by radare** [comment]
Yeah looks like it should be working now :) will wait until next release, im still playing with it. So i guess we can close that issue for now.

**Comment by oleavr** [comment]
👍
