### ISSUE TITLE
Spawn on Android crashes zygote

### ISSUE THREAD

**Issue by karan-dash** [frida/frida-gum#142]
Hello. I'm trying to use frida v6.2.1 on Android 4.2.2 emulator. Android crashes after I'm trying to spawn process with command **frida -U -f com.android.browser**. 
Similar problem I've got trying to run spawn on device. 
Attaching works without any problem.

*_logcat: *_
E/Zygote  ( 1127): Zygote died with exception
E/Zygote  ( 1127): java.lang.RuntimeException: Error in select()
E/Zygote  ( 1127):  at com.android.internal.os.ZygoteInit.runSelectLoopMode(ZygoteInit.java:647)
E/Zygote  ( 1127):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
E/Zygote  ( 1127):  at dalvik.system.NativeStart.main(Native Method)
E/Zygote  ( 1127): Caused by: java.io.IOException: Invalid argument
E/Zygote  ( 1127):  at com.android.internal.os.ZygoteInit.selectReadable(Native Method)
E/Zygote  ( 1127):  at com.android.internal.os.ZygoteInit.runSelectLoopMode(ZygoteInit.java:645)
E/Zygote  ( 1127):  ... 2 more
D/AndroidRuntime( 1127): Shutting down VM
W/dalvikvm( 1127): threadid=1: thread exiting with uncaught exception (group=0x40a71930)

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
