### ISSUE TITLE
Java reflection do not get correct result

### ISSUE THREAD

**Issue by 3asm** [frida/frida-gum#143]
Hi,

Testing on Android emulator ARM 4.4.2 with latest frida-server. The following sample code crashes silently:

``` javascript
        send("element: " + element);
        send("element.getClass: " + element.getClass());
        send("element.getClass.getDeclaredFields: " + element.getClass().getDeclaredFields());
```

Giving the following results:

```
[+] element: android.content.UriMatcher@b1d01c28
[+] element.getClass: class android.content.UriMatcher
```

element.getClass() is supposed to return an instance of `java.lang.Class`.

By the way, is there a way to attach a debugger to running Javascript code ? I didn't see anything in the doc.

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-java#6.
