### ISSUE TITLE
gum-tests /Core/Backtracer/full_cycle segfaults on linux-arm 

### ISSUE THREAD

**Issue by unraised** [frida/frida-gum#144]
The issue here is that the frida-gum code that intercepts calls to _dl_runtime_resolve doesn't save r12.

Reproducible with qemu's user-mode arm emulation:

    qemu-arm -L /path/to/linux-arm-fs-chroot build/tmp-linux-arm/frida-gum/tests/gum-tests -p /Core/Backtracer/full_cycle

The /Core/Backtracer/full_cycle test intercepts calls to _dl_runtime_resolve from the .plt code that resolves .plt entries. The _dl_runtime_resolve API for arm uses r12 (aka the 'ip' register) [API documented here](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/arm/dl-trampoline.S;h=3c75be738e78e600e15cf153b886975cd83bb29f;hb=HEAD). R12 is initialized before the interception of the call, but r12 is not saved during interceptor execution.

Consider what happens when the _dl_runtime_resolve interceptor is enabled and a .plt entry needs resolved. First r12 is set to the appropriate value  for the _dl_runtime_resolve arm API. Then execution is transferred to frida-gum as it intercepts the .plt code calling _dl_runtime_resolve. If the frida-gum interceptor code calls any library functions via the .plt., the original, unsaved r12 value is trashed by the .plt code (even if the symbol is already resolved). Thus, when the interceptor code finishes and control is returned to the intercepted _dl_runtime_resolve, r12 is no longer the correct value.

**Comment by oleavr** [comment]
Whoah, thanks for the excellent analysis! This should now be fixed as of this patch:
https://github.com/frida/frida-gum/commit/767742f76b29b3ba586df1a5743381e7e4236cf5

Cheers!

**Comment by oleavr** [comment]
Frida 6.2.5 is out now containing this fix. Sorry for the delay btw, hope it works better for you now!

**Comment by unraised** [comment]
Ah, it would work except that the wide opcodes for the push/pops are Thumb2, so cpus with only armv5t support (the one I'm looking at) throw an illegal instruction exception. Are you planning to support armv5t or just focus on newer architectures? For armv5t, if you want to save high registers R8-R12, then the trampolines should be implemented in arm.

**Comment by oleavr** [comment]
@unraised Ahh oops, good point. It would be great to detect lack of Thumb2 and perform those operations in ARM mode. The challenge for me is that I cannot test such a workaround. Do you feel like taking a stab at it?
