### ISSUE TITLE
JavaScript API can't handle 64-bit integers

### ISSUE THREAD

**Issue by Tyilo** [frida/frida-gum#16]
Moved from https://github.com/frida/frida/issues/18

<hr>

As Numbers in JavaScript are stored as doubles, they can't represent all 64-bit integers.

Problematic example:
```
$ cat > fail.c
#include <stdio.h>
#include <stdint.h>

uint64_t a = 0x8888888888888888;
uint64_t b = 0x8888888888888889;

int main(void) {
	printf("&a, a: 0x%p, %llu\n", &a, a);
	printf("&b, b: 0x%p, %llu\n", &b, b);
	getchar();

	return 0;
}
^D
$ cc fail.c -o fail
$ ./fail
&a, a: 0x0x108520020, 9838263505978427528
&b, b: 0x0x108520028, 9838263505978427529

(leave running)
```

```
$ frida-repl fail
Attaching...
>>> a = Memory.readU64(ptr('0x108520020'))
9838263505978427000
>>> b = Memory.readU64(ptr('0x108520028'))
9838263505978427000
>>> a == b
true
```

As you can see the JavaScript API thinks that the memory contents of `a` and `b` are the same, when they in fact differ by 1.

**Comment by oleavr** [comment]
This has now become a blocker for me, so I've started reworking this here:
https://github.com/frida/frida-gum/tree/fix/int64-handling

**Comment by oleavr** [comment]
Fixed in latest master. New major release coming soon.
