### ISSUE TITLE
Access violation on apply'ing integer argument

### ISSUE THREAD

**Issue by dpnishant** [frida/frida-gum#165]
The script below

```
var getSharedPreferences = ContextWrapper.getSharedPreferences.overload("java.lang.String", "int");
getSharedPreferences.implementation = function (spName, spMode) {
  console.log('getSharedPreferences Name: ' + spName);
  return getSharedPreferences.apply(this, arguments);
};
```

is throwing different types of errors (mostly access violation) in different apps.

<img width="1440" alt="screen shot 2016-06-26 at 1 33 33 pm" src="https://cloud.githubusercontent.com/assets/1339669/16389610/570da2fe-3cbc-11e6-9630-a74054aa949e.png">

<img width="1440" alt="screen shot 2016-06-26 at 1 47 08 pm" src="https://cloud.githubusercontent.com/assets/1339669/16389609/570c98b4-3cbc-11e6-968a-30d9fef4b12a.png">

<img width="1440" alt="screen shot 2016-06-26 at 1 48 59 pm" src="https://cloud.githubusercontent.com/assets/1339669/16389611/570f1d28-3cbc-11e6-9684-537695420be5.png">

<img width="871" alt="screen shot 2016-06-27 at 11 10 41 pm" src="https://cloud.githubusercontent.com/assets/1339669/16389635/722b0fcc-3cbc-11e6-884e-11079ccf4a15.png">

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-java#5.
