### ISSUE TITLE
Too many PopLocalFrame calls

### ISSUE THREAD

**Issue by dpnishant** [frida/frida-gum#166]
This following script initially works as normal initially

```
if (ContextWrapper.getCacheDir) {
        // Ref: https://developer.android.com/reference/android/content/ContextWrapper.html#getCacheDir()
        ContextWrapper.getCacheDir.implementation = function() {
            var cache_dir = this.getCacheDir.call(this);
            console.log('Cache Dir: ' + cache_dir.toString());
            return cache_dir;
        };
    }
```

but after a while (after certain amount of interaction with the app) it throws the following error.

![screen shot 2016-06-28 at 4 43 08 pm](https://cloud.githubusercontent.com/assets/1339669/16413516/015aa03e-3d50-11e6-8f7d-17dd779d140c.png)

**Comment by oleavr** [comment]
Interesting. It looks like we may have a code-path where we don't properly balance the PushLocalFrame and PopLocalFrame calls.

**Comment by oleavr** [comment]
Let's keep tracking this at frida/frida-java#3.
