### ISSUE TITLE
Issues with Java.choose

### ISSUE THREAD

**Issue by dirkjanm** [frida/frida-gum#171]
I'm trying to execute methods with objects in memory.
However this always fails with the following error:

```
TypeError: Cannot read property '$handle' of undefined
    at String.toJni (gumjs-java.js:2051:33)
    at String.someMethod (eval at makeMethod (gumjs-java.js:1241:17), <anonymous>:1:343)
    at Object.onMatch (repl7.js:64:101)
    at vm.perform (gumjs-java.js:513:61)
    at VM.perform (gumjs-java.js:2110:17)
    at onMatch (gumjs-java.js:502:32)
```

I've tried to debug this a bit with the node debugger, the issue however seems to be with the instance passed to the callback function. The instance never has any value for $handle or $classHandle:

```
{ '$classWrapper': [Function: val],
  '$classHandle': {},
  '$handle': {},
  '$weakRef': 13 }
```

Is this intended behaviour or am I doing something wrong? What would be the recommended way of calling a static method of a class with an instance as parameter?

**Comment by oleavr** [comment]
Let's assume this is fixed in the latest [frida-java](https://github.com/frida/frida-java).
