### ISSUE TITLE
Application stop work when getting hook

### ISSUE THREAD

**Issue by zfn-ww** [frida/frida-gum#175]
I'm trying to hook many Object-C functions in one iOS application, but the application always stop work on a specific function. But nothing happened but when I tested it alone.
I got one log like below.
Oct 19 17:50:49 iPhone JD4iPhone[742] <Error>: Frida: frida-gum/gum/backend-darwin/gummemory-darwin.c:370:gum_alloc_n_pages: assertion failed (kr == KERN_SUCCESS): (3 == 0)
It seems like a memory leak?
Test on iPhone 5c & iOS 9.0.1.
frida version is 8.1.1.

**Comment by oleavr** [comment]
Should be fixed in latest Frida 9.x.
