### ISSUE TITLE
DebugSymbol.fromAddress / .fromName returning wrong names

### ISSUE THREAD

**Issue by oleavr** [frida/frida-gum#186]
(Continuation of frida/frida#206.)

As described by @doegox:

Playing around with symbols in a linux libc...

```
let a=DebugSymbol.findFunctionsMatching("_I?_do_write")[0];
DebugSymbol.fromAddress(a);
```
=> `{'moduleName': 'libc.so.6', 'name': '_IO_do_write', ...}`
=> ok

```
let a=DebugSymbol.findFunctionsMatching("_I?_fwrite")[0];
DebugSymbol.fromAddress(a);
```
=> `{'moduleName': 'libc.so.6', 'name': 'fwrite', ...}`
=> 'fwrite' <> '_IO_fwrite' ??

`DebugSymbol.fromName("fwrite"))`
=> empty data

`DebugSymbol.fromName("_IO_fwrite"))`
=> `{'moduleName': 'libc.so.6', 'name': 'fwrite', ...}`
=> 'fwrite' <> '_IO_fwrite' ??

And on Android I get always empty names:

```
let a=DebugSymbol.findFunctionsMatching("fwrite")[0];
DebugSymbol.fromAddress(a);
```
`{'address_hex': '0x4003db0c', 'name': '', 'fileName': '', 'moduleName': 'libc.so', 'lineNumber': 0, 'address': 1073994508}`

**Comment by oleavr** [comment]
Should be fixed in Frida 10.6.4.

**Comment by doegox** [comment]
Please reopen.
Now that #240 is fixed, I tested it and I've still almost the same issues as before:

    send(DebugSymbol.fromAddress(DebugSymbol.findFunctionsMatching("_I?_do_write")[0]));

=> `{'address': '0x7fe64e1b38c0', 'name': '_IO_do_write', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}`

ok

    send(DebugSymbol.fromAddress(DebugSymbol.findFunctionsMatching("_I?_fwrite")[0]));

=> `{'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}
`

'fwrite' <> '_IO_fwrite' ??

    send(DebugSymbol.fromName("fwrite"));

=> `{'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}`

Used to be empty but now returns 'fwrite'??

    send(DebugSymbol.fromName("_IO_fwrite"));

=> `{'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}`

'fwrite' <> '_IO_fwrite' ??

**Comment by oleavr** [comment]
> send(DebugSymbol.fromAddress(DebugSymbol.findFunctionsMatching("_I?_fwrite")[0]));
> => {'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}
>
> 'fwrite' <> '_IO_fwrite' ??

```
$ nm -D /lib/x86_64-linux-gnu/libc.so.6 | grep fwrite
00000000000773d0 W fwrite
00000000000773d0 T _IO_fwrite
```

Some addresses have more than one symbol pointing at them.

> send(DebugSymbol.fromName("fwrite"));
> => {'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}
>
> Used to be empty but now returns 'fwrite'??

So this is an improvement over how it used to be, isn't it?

> send(DebugSymbol.fromName("_IO_fwrite"));
> => {'address': '0x7fe64e1a7f50', 'name': 'fwrite', 'moduleName': 'libc.so.6', 'fileName': '', 'lineNumber': 0}
>
> 'fwrite' <> '_IO_fwrite' ??

This is because `DebugSymbol.fromName()` is implemented by first looking up the address from the name, and then getting symbol details from the address. The problem is that multiple symbols may resolve to the same address, so it's not well-defined which one you're going to get in the reverse lookup. We could solve this by making the underlying API richer, but that means changing all three implementations. (PR welcome!)

**Comment by doegox** [comment]
Ha thank you, I understand my mistake, sorry for the noise.

**Comment by doegox** [comment]
What about

> And on Android I get always empty names:
> `let a=DebugSymbol.findFunctionsMatching("fwrite")[0];`
> `DebugSymbol.fromAddress(a);`
> `{'address': '0x4003db0c', 'name': '', 'fileName': '', 'moduleName': 'libc.so', 'lineNumber': 0}`

If I try now the same code on Android (4.4) and Frida 10.6.11 I get even less info

`{'address': '0x4009eb0d', 'name': None, 'moduleName': None, 'fileName': None, 'lineNumber': None}`

Same for all addresses returned by DebugSymbol.findFunctionsMatching("*").

**Comment by oleavr** [comment]
> Ha thank you, I understand my mistake, sorry for the noise.

Nah no worries, this is a usability bug as it's very confusing.

> If I try now the same code on Android (4.4) and Frida 10.6.11 I get even less info

We now use `dladdr()` to fill in the blanks when we don't have debug symbols. Sounds like this doesn't actually work that well on Bionic. Sounds like we'll need a fallback, using `Gum.Module.enumerate_exports()` when `dladdr()` fails. Hmm. Food for thought.
