### ISSUE TITLE
Possible license concern due to bfd.h

### ISSUE THREAD

**Issue by ChaosData** [frida/frida-gum#197]
Hi,

It appears that the `gum_find_function*` implementations for ELF-based systems (implemented in <https://github.com/frida/frida-gum/blob/9ad62881e22f05ba478ef7fad1577dddef3e9421/gum/backend-bfd/gumsymbolutil-bfd.c>) rely on `bfd.h` from binutils to parse ELF binaries and extract their symbols. `bfd.h` is explicitly GPL-licensed, which would make it appear that any binary releases of frida-gum (or things containing it) that contain the `bfd.h`-based `gum_find_function*` functions would be GPL'd. The build process itself only uses that implementation if the binutils development headers (such as `bfd.h`) are actually installed, which is not a given default, but possibly a common configuration among folks who might be building frida (or subcomponents) from source.

I wasn't able to find any information referencing this, and it seems to counteract one of the points of using the wxWindows Library license (or the LGPL before it), so I just thought that I'd point it out.

**Comment by oleavr** [comment]
Great catch! Much appreciated – I've gone to great lengths to avoid GPL-dependencies, but this one was a long missed oversight.  This does indeed only concern the Linux `Gum.SymbolUtil` backend (exposed as `DebugSymbol` in the JS bindings). There's been quite a few complaints about technical issues concerning this backend, so I think it's time to kick out the `bfd` backend and write a new one.

**Comment by oleavr** [comment]
Fixed in Frida 10.6.4. We are now using libelf + libdwarf.
