### ISSUE TITLE
Regression when loading scripts?

### ISSUE THREAD

**Issue by alvarofe** [frida/frida-gum#204]
First of all if this is not the correct place to report point me out in the right repository.

I updated frida to 9.1.8 in node and I observed issues when trying to create a session basically timeouts issues. Here an asciinema (9.1.7 in the example and it fails in 9.1.8 too). With 9.1.6 everything works fine.

https://asciinema.org/a/af9te6l4h5vpb1zivdd6exp0g

Can you reproduce?

```
air:~ alvaro$ frida --version
9.1.18 
```

**Comment by alvarofe** [comment]
This seems to be fixed already.

**Comment by oleavr** [comment]
Thanks for confirming @alvarofe! 🍻
