### ISSUE TITLE
New release changelog

### ISSUE THREAD

**Issue by max01203** [frida/frida-gum#208]
Hi,
It's not a real issue but I don't know where to really contact you. I've seen that for each release you say that we check the news page of Frida. But I don't know if it's me that I've a problem but in this page there is only information about major release and not for instance difference between 1.18 and 1.19 and so on is it normal?

Thanks,

**Comment by oleavr** [comment]
Hey,

This is my fault, still need to write the 9.1 release notes and append changelog items for the patch-releases following it.

By the way, feel free to join https://t.me/fridadotre

Cheers!
