### ISSUE TITLE
Port Stalker to Duktape

### ISSUE THREAD

**Issue by manizzle** [frida/frida-gum#209]
Duktape bindings for Stalker have not been implemented. This issue is just to track the ongoing work with it, questions, etc. This is my first time working with a JS engine. 

Duktape Docs:
http://duktape.org/guide.html#programming

Reference Implementation:
https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8stalker.cpp

Current (known) work:
- Duktape version of https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8eventsink.cpp
- Implement _follow, unfollow, addCallProbe, and removeCallProbe

**Comment by manizzle** [comment]
Personal Notes. If I am wrong, please clarify!

https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8stalker.cpp#L265 
- these args are used for decoding the arguments given to gumjs_stalker_follow function
-- https://github.com/frida/frida-gum/blob/master/bindings/gumjs/runtime/core.js#L539
-- args are created in the helper function: https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumdukmacros.h#L67

Now, when we call https://github.com/frida/frida-gum/blob/master/gum/gumstalker.h#L76, we need an GumEventSink object.

V8 has one in its GumV8Stalker object, but Duktape does not:

https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8stalker.h#L12
https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumdukstalker.h#L16

The EventSink is the mechanism by which callbacks are handled, and called by the stalker process. This needs to be implemented for DukTape.

Currently, only V8 EventSink's exist:

https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8eventsink.cpp
https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumv8eventsink.h

**Comment by oleavr** [comment]
> these args are used for decoding the arguments given to gumjs_stalker_follow function

Correct; we expose `_follow()`, and `follow()` is implemented in JS, allowing the complex argument validation rules to be shared between V8 and Duktape.

> The EventSink is the mechanism by which callbacks are handled, (...)

Yep, that's right. We deliver the events in batches to JS to improve performance, except for call probes, which are executed synchronously in JS.

**Comment by oleavr** [comment]
Implemented back in July.
