### ISSUE TITLE
arm_relocator BUG

### ISSUE THREAD

**Issue by asLody** [frida/frida-gum#213]
```c
static gboolean
gum_arm_relocator_rewrite_b (GumArmRelocator * self,
                             cs_mode target_mode,
                             GumCodeGenCtx * ctx)
{
  const cs_arm_op * target = &ctx->detail->operands[0];

  if (target->type != ARM_OP_IMM)
    return FALSE;

  gum_arm_writer_put_ldr_reg_address (ctx->output, ARM_REG_PC,
      (target_mode == CS_MODE_THUMB) ? target->imm | 1 : target->imm);
  return TRUE;
}
```
It just convert `b #offset` to `ldr pc, #offset`, in fact, the repair is invalid.

**Comment by oleavr** [comment]
The `b #offset` is position-dependent, so it turns it into `ldr pc, #address`, which is not. (It could be improved to use a `b #offset` if the target is nearby.) Do you have a testcase where this logic doesn't hold true?

**Comment by asLody** [comment]
Binary code of the function has been split into **two** parts( `the head`  and  `the content`  ), 
 If we use **b instruction** from head to jump to content, the location of the PC will be wrong. So we should compute the `absolute pc`.

**Comment by oleavr** [comment]
`target->imm` is already the `absolute pc` – Capstone already calculated it for us.
