### ISSUE TITLE
NativeFunction.apply() doesn't work, but .call() does

### ISSUE THREAD

**Issue by geekman** [frida/frida-gum#214]
I don't know enough of Duktape internals to debug this.

The following code snippet shows that when `.apply` is called, it says "Error: invalid argument value", but it is working fine when `.call` is used instead.

```
var a = new NativeFunction(ptr(0x4000), 'void', ['pointer', 'int']);
a.apply(null, [ptr(0), 0]);  // <-- this causes error
a.call(null, ptr(0), 0);
```

I believe both the `.apply` and `.call` statements above are semantically identical.

It works fine when there's only 1 argument to the native function, like so:
```
var a = new NativeFunction(ptr(0x4000), 'void', ['pointer']);
a.apply(null, [ptr(0)]);
a.call(null, ptr(0));
```

**Comment by oleavr** [comment]
Thanks a lot for reporting! Fixed.
