### ISSUE TITLE
Issue with ObjC _printHierarchy

### ISSUE THREAD

**Issue by Nightbringer21** [frida/frida-gum#224]
Trying to call the _printHierachy method from the UIViewController leads to `undefined`, even though the method is returned both from the `$methods` and from the tab completion of the frida cli.

Example call:
`ObjC.classes.UIViewController._printHierarchy`
Response:
`undefined`

Way around to make the exact same call:
`ObjC.classes.UIViewController.valueForKeyPath_('_printHierarchy').toString()`

**Comment by oleavr** [comment]
Method names containing underscores have to be accessed like this:
ObjC.classes.UIViewController['- _printHierarchy']();
(Because we map `:` to `_` for convenience.)
