### ISSUE TITLE
Calling variadic function fails

### ISSUE THREAD

**Issue by nioncode** [frida/frida-gum#235]
When calling a native function with variadic args, frida raises a `RPCException`:
```
Traceback (most recent call last):
  File "android-hook.py", line 26, in <module>
    script.exports.init()
  File "/home/nioncode/frida/lib/python3.6/site-packages/frida/core.py", line 425, in method
    return script._rpc_request('call', js_name, args)
  File "/home/nioncode/frida/lib/python3.6/site-packages/frida/core.py", line 355, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: bad argument count
    at script1.js:194
    at apply (native)
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:25)

```

Code to trigger:
```javascript
var ANDROID_LOG_DEBUG = 3;
var print = Module.findExportByName(null, "__android_log_print");
var log = new NativeFunction(print, 'int', ['int', 'pointer', 'pointer', '...']);
var tag = Memory.allocUtf8String('frida');
var format = Memory.allocUtf8String("hello %s");
var msg = Memory.allocUtf8String("world");
log(ANDROID_LOG_DEBUG, tag, format, msg);
```

**Comment by oleavr** [comment]
Hi,

The `NativeFunction` you create must have the exact signature, i.e. you need one per permutation of variadic arguments. E.g. for you example it must be:

`var log = new NativeFunction(print, 'int', ['int', 'pointer', 'pointer', '...', 'pointer']);`

Cheers!

**Comment by nioncode** [comment]
So the last `pointer` argument specifies that the variadic `...` refers to a list of pointers?
Why is this necessary? In C there is only the trailing `...` without any type information.

**Comment by oleavr** [comment]
No, `...` denotes that:
1) the function is varargs
2) the fixed arguments stop there, and anything after are dynamic arguments
This is required by the libffi API, which Frida uses under the hood. In C you have a compiler that knows what types are used in each call site, so it generates different code depending on that.
