### ISSUE TITLE
DebugSymbol functions don't see most of functions since 10.6.4

### ISSUE THREAD

**Issue by doegox** [frida/frida-gum#240]
It seems something went wrong when fixing issue #186 
Trying ```DebugSymbol.findFunctionsMatching("*")``` on a ```/bin/cat``` on Linux...

With versions <= 10.6.3 I get 2096 results from frida-agent-64.so, ld-linux-x86-64.so.2, libc.so.6, libdl.so.2, libm.so.6, libpthread.so.0, libresolv.so.2, librt.so.1

With versions >= 10.6.4 I get 538 results, all from libpthread.so.0 (while BTW previously out of the 2096, only 456 came from libpthread.so.0)

And trying e.g. `getFunctionByName` on known functions fails too.

**Comment by oleavr** [comment]
Oh wow, sorry about that, I broke things pretty badly. Thanks for the heads up!

**Comment by doegox** [comment]
I don't know if it's related but if I enumerate ranges *after* having called DebugSymbol functions, I get extra ranges with a read-only copy ('r--') of everything: main exec & libs.

**Comment by oleavr** [comment]
@doegox That's okay. As of 10.6.4 we lazily `mmap()` them into memory to read their symbols, and keep them mapped until unload to avoid repeatedly opening and closing them for subsequent lookups.

Fix released in 10.6.11.

Cheers!

**Comment by doegox** [comment]
Thanks!
