### ISSUE TITLE
Interceptor does not work with variadic C++ function

### ISSUE THREAD

**Issue by leoluk** [frida/frida-gum#243]
Intercepting a variadic C++ function does not appear to work.

Example signature:

```
void Log_VA(Verbosity::Type Verbosity, const TCHAR * Fmt, ...)
``` 

No error message, it simply never triggers. Setting a debugger break point at the same address works. Is this a known limitation?

**Comment by thejunkjon** [comment]
Check that the symbol name is correct.  You will need to use the mangled name.
https://en.wikipedia.org/wiki/Name_mangling#Simple_example

**Comment by oleavr** [comment]
Interceptor is completely agnostic to the particular calling convention and argument list, so as @thejunkjon pointed out this must be caused by not finding the function to intercept.

**Comment by leoluk** [comment]
Here's example code:

```
var f_log_ptr = DebugSymbol.findFunctionsNamed("Log_VA")[0];

console.log("Log_VA is at", f_log_ptr);

Interceptor.attach(f_log_ptr, {
  onEnter: function(args) {
        console.log("We entered the interceptor");

        console.log("Log function called from:\n" +
                Thread.backtrace(this.context, Backtracer.ACCURATE)
                .map(DebugSymbol.fromAddress).join("\n") + "\n");
  
        for (var i = 0; i < 10; i++) {
                console.log(i, args[i]);
        }
  }
});
```
The address in `f_log_ptr` is correct. If I set a breakpoint using a debugger at the same address, it fires but nothing happens with the interceptor. How would I go about debugging this?

**Comment by oleavr** [comment]
Thanks. Which binary?

**Comment by leoluk** [comment]
Can I send it to you over a private channel? It's proprietary.
