### ISSUE TITLE
test is writing a 64bit value in a 32bit variable

### ISSUE THREAD

**Issue by akiannillo** [frida/frida-gum#245]
line in

https://github.com/frida/frida-gum/blob/f1d085393614272527b801bba559c31c5ef51e3f/tests/core/arch-arm64/stalker-arm64-fixture.c#L153

should be substituted by
`gum_arm64_writer_put_str_reg_reg_offset (&cw, ARM64_REG_W0, ARM64_REG_X1, 0);`

**Comment by oleavr** [comment]
Thanks!
