### ISSUE TITLE
Interceptor.replace doesnt work on Android 4.4 x86 (bluestacks) since v10.6.12

### ISSUE THREAD

**Issue by va1d3z** [frida/frida-gum#249]
NativeCallback not called when intercepted function exetues

**Comment by henrymark92** [comment]
Hello @va1d3z 
Can you help me fix this issue?
https://github.com/frida/frida/issues/405

**Comment by oleavr** [comment]
Fixed in Frida 10.6.39, currently being released. Cheers!

**Comment by wazzygray** [comment]
> Fixed in Frida 10.6.39, currently being released. Cheers!

How to attach frida with bluestacks?
