### ISSUE TITLE
Hello,can anybody tell me what is frida-gum?

### ISSUE THREAD

**Issue by SimonKoh** [frida/frida-gum#251]
I came here from frida C API page , and I thought maybe frida-gum is a different way to inject my "C code" in target process,or I've got something wrong,it just a another way to inject google V8 engine in target process to run my js code.I am wondering what  the different frida-gum and frida-core is,,Because my js is not well... 
Thanks guys! : )

**Comment by oleavr** [comment]
Just added a README here to provide an overview:
https://github.com/frida/frida-gum

See the architecture diagram here:
https://frida.re/docs/hacking/

**Comment by SimonKoh** [comment]
Thank you！
