### ISSUE TITLE
How to inject some Java classes, so that we can get using Java.use("my_class")  (Android)

### ISSUE THREAD

**Issue by waqarrashid33** [frida/frida-gum#257]
Hey,
I am trying to replace Droidmon in CuckooDroid by Frida. Hooking the methods is simple enough but to make to integrate Frida with CuckooDroid, I need to write a lot of logging code which is already available in Droidmon source code. Is there a way that I can call these logging methods, instead of reimplementing them in JavaScript.

It would be a lot better if somehow I can access these classes using Java.use("class_name") like other classes. The device is rooted and I don't want any repackaging of APK.

I hope I explained myself, feel free to ask for more clarification.
Waqar

**Comment by oleavr** [comment]
Try:

```js
var dexFile = Java.openClassFile('/path/to/my.dex');
// console.log(dexFile.getClassNames().join('\n'));
dexFile.load();
```
