### ISSUE TITLE
Stalker stop following after a read syscall on x86_64

### ISSUE THREAD

**Issue by andreafioraldi** [frida/frida-gum#295]
Callbacks inserted with iterator.putCallout in Stalker.follow are not called anymore after a read syscall.
I attach an example script that log executed instructions, a binary that calls read and a trace of the script applied to the binary.

I missed something or is a bug? If it's the first case, how can use Stalker with this syscall?

[Attachments](http://andreafioraldi.altervista.org/foo.tar.gz)

ps. in the trace is not shown but I inserted "a"*40 when the program asked for the input

**Comment by oleavr** [comment]
Hmm, does this work better if you drop the transform callback and use `events: { exec: true }`? That will give you one event per instruction (slow).

**Comment by andreafioraldi** [comment]
The instruction tracer is just an example, i need transform for taint-analysis.

**Comment by oleavr** [comment]
I’m not suggesting a workaround, I’m trying to narrow down where the bug is.

**Comment by andreafioraldi** [comment]
Ok, the problem is present also with exec.
I will send an example later when i'm at home. If you want to reproduce the bug I'm using mint 18 x86_64.

**Comment by andreafioraldi** [comment]
The problem is not anything relevant.
The tracing restarts simply sending some new lines after the input (also if the input is longer than the read request). 
With exec, instead, onReceive is called before (or during?) the read and sending new lines doesn't restart the tracing.
IDK if this a normal behavior but forcing to send extra newlines can broke a script that sends the input if present.

**Comment by andreafioraldi** [comment]
For reference:
I solved using
```
def wait_polling(pid):
    while True:
        try:
            os.kill(pid, 0) #signal 0 does nothing
        except OSError:
            return
        time.sleep(1)
```
instead of `sys.stdin.read()` in the python script.
