### ISSUE TITLE
Stalker does not work for cross-thread injection on Android

### ISSUE THREAD

**Issue by josiahyan** [frida/frida-gum#330]
When trying to use Stalker on a release copy of an Android application on aarch64 that has multiple threads, Stalker returns no output when asking for call summaries. I believe I have identified two issues.

### `ptrace` code injection failed
Stalker appears to fail on the spawned child thread attaching to the other thread of the existing parent process:

https://github.com/frida/frida-gum/blob/83b2601ec7161b883bcc996260a3cae17d04696c/gum/backend-linux/gumprocess-linux.c#L411-L421

I believe this is because the target process "dumpable" attribute is 0, [when it should be 1 for `ptrace` to work](http://man7.org/linux/man-pages/man2/ptrace.2.html). Setting of this attribute to 0 for release applications (in most scenarios) is mandated by the [Android CTS](http://androidxref.com/8.0.0_r4/xref/cts/tests/tests/os/src/android/os/cts/SecurityFeaturesTest.java#48).

This issue disappeared after switching my application to a debug build.

### Code writer omitted some branch instructions
I encountered a separate issue even after ptrace works. Stalker uses gum's code writer to initialize a block of code that sets up Stalker in the remote thread. Unfortunately, branch instructions were elided from my copy of the prologue setup code. This did not happen on the Stalker test cases, but only occurred in my application.

Specifically, the following function calls to write the branches may return false, and this was not checked for: 

https://github.com/frida/frida-gum/blob/83b2601ec7161b883bcc996260a3cae17d04696c/gum/backend-arm64/gumstalker-arm64.c#L1517

https://github.com/frida/frida-gum/blob/83b2601ec7161b883bcc996260a3cae17d04696c/gum/backend-arm64/gumstalker-arm64.c#L1531

This would occur when the code thunks were too far away from the executed region, as seen here:

https://github.com/frida/frida-gum/blob/f8c04fa3547a3fae5bbd27d7e9d1352af9ee4e30/gum/arch-arm64/gumarm64writer.c#L508-L521

I tried saving X16 and calling a variant of `gum_arm64_writer_put_branch_address` in the prologue and epilogue code, which would handle the far address case. This seemed to result in a fix, and Stalker seemed to run successfully for the first few basic blocks, but `gumstalker-arm64.c` appears to have other instances where a branch instruction to a far address would be omitted, causing it to fail.

Should I attempt to push a fix for the first issue? I think this can be solved by calling `prctl(PR_{GET, SET}_DUMPABLE )` to set and restore the "dumpable" attribute before attempting injection, on the Android platform.

I'm not quite sure how the second issue should be solved, given that branching to a register would always clobber some register (in this case X16)? One way might be to repeat the same approach for the epilogue/prologue case, but I'm unfamiliar with the register convention for Stalker on aarch64.

@akiannillo

**Comment by oleavr** [comment]
Thanks for digging into this – awesome detective work!

> Should I attempt to push a fix for the first issue? I think this can be solved by calling prctl(PR_{GET, SET}_DUMPABLE ) to set and restore the "dumpable" attribute before attempting injection, on the Android platform.

That would be great! Sounds like a good solution.

> I'm not quite sure how the second issue should be solved, given that branching to a register would always clobber some register (in this case X16)?

Stalker is meant to generate another set of helpers as soon as the distance between the previous set of helpers and the current position reaches the `BL` instruction's maximum displacement. So that means there's a bug in that logic and we need to figure out why this fails. Would you be interested in taking a stab at it?

**Comment by josiahyan** [comment]
Okay sure! I'll test and get a small PR out for the first issue, and take a closer look at the second. Thanks for the tips!
