### ISSUE TITLE
Missing typescript declaration

### ISSUE THREAD

**Issue by gebing** [frida/frida-gum#337]
Following typescript declaration is missing from `frida-gum.d.ts`:

```
declare interface NativeFunction {
  (...args: NativeArgumentValue[]): NativeReturnValue;
}
```

**Comment by oleavr** [comment]
Thanks for reminding me about this one. It's been a lingering issue as I initially didn't see a way to make them `NativePointer` values in addition to being callable functions. But took another look now and found a way. Just released `frida-gum-types@5.0.6`. Cheers!
