### ISSUE TITLE
mesage-dispatcher broken since latest commit

### ISSUE THREAD

**Issue by bannsec** [frida/frida-gum#363]
Looks like the latest commit broke the `message-dispatcher.js`:

https://github.com/frida/frida-gum/commit/59d614c7185bb520c93cc4d8d4465c87ad466b32#diff-494be477a372e43c14d43d8f03e51dfa

Specifically, since that change I get the following error from frida:

```
{'type': 'error', 'description': 'TypeError: complete is not a function', 'stack': 'TypeError: complete is not a function\n    at dispatch (frida/runtime/message-dispatcher.js:100:1)\n    at Array.forEach (<anonymous>)\n    at dispatchMessages (frida/runtime/message-dispatcher.js:79:1)\n    at handleMessage (frida/runtime/message-dispatcher.js:32:1)', 'fileName': 'frida/runtime/message-dispatcher.js', 'lineNumber': 100, 'columnNumber': 1}
```

It appears that complete is no longer a function, and thus when it is attempted to be called frida errors out.

EDIT: For anyone looking to use this functionality, you can revert Frida back to `12.7.9` with `pip install -U frida==12.7.9`.

**Comment by mrmacete** [comment]
Interesting, can you share a reproducer for this?

**Comment by bannsec** [comment]
Sure. Gonna take a little before i can boil it down into a frida specific test script.

The main reason I found this is because it broke one of my unit tests:

https://github.com/bannsec/revenge/blob/master/tests/linux/contexts/test_batch_context.py

If you install revenge git master and run pytest on that test_batch_context.py you will see the same error. Or more-so, it will hang and you will see the error once you ctrl-c it.

**Comment by mrmacete** [comment]
ok, thanks. managed to reproduce (also on macOS). looking at it!

**Comment by bannsec** [comment]
Any ideas on it?

**Comment by oleavr** [comment]
@bannsec Yes, @mrmacete discovered it's a bug in V8, and exactly which commit fixed it. Currently releasing 12.7.12 with the fix cherry-picked.

**Comment by oleavr** [comment]
@bannsec It's out if you want to take a stab at verifying the fix. (Hopefully I didn't screw things up.)

**Comment by bannsec** [comment]
My tests pass now. Thanks!

**Comment by oleavr** [comment]
Yay. Thanks for confirming!
