### ISSUE TITLE
Support variadic function for `NativeCallback`  

### ISSUE THREAD

**Issue by gebing** [frida/frida-gum#364]
`NativeCallback` can only be created by specific arguments and do not support variadic function  like `NativeFunction`. 

I  know it is because frida-gum can not determine the actual count of arguments when invoking NativeCallback by libffi. I look up the code of [pyobjc](https://bitbucket.org/ronaldoussoren/pyobjc), think we can use pyobjc's solution. That is marking the variadic argument by specify the count resolve  method, such as: 'c_array_delimited_by_null', or 'c_array_length_in_arg: index'.

@oleavr 
If you agree with this enhancement, I can try to implement.

**Comment by oleavr** [comment]
Ah yes, would be nice to solve this.

That sounds like a simple solution that covers most of the cases; let's try that!

**Comment by gebing** [comment]
I looked at the source code of `libffi` and found it is impossible due to  the way `libffi` works. 

When a native call is made on the closure by `ffi_prep_closure_loc`, the `libffi` only pass the specific arguments which declared by `ffi_prep_cif`/`ffi_prep_cif_var` to target function. So the target function, which is `gum_duk_native_callback_invoke`/`gum_v8_native_callback_invoke`  in `frida-gum`, does not have any means to get the real call stack of original invocation, and therefore it can not parse for the variadic arguments.

**Comment by oleavr** [comment]
Ahh I see. Thanks for looking into that!
