### ISSUE TITLE
flush buffer at exit

### ISSUE THREAD

**Issue by bannsec** [frida/frida-gum#378]
For short living programs, there's a race condition where frida will not fully empty it's send buffer back to python. It would be helpful to have frida register atexit or similar and ensure that the data waiting in the send buffer actually gets sent.

**Comment by oleavr** [comment]
It already does this:
https://github.com/frida/frida-core/blob/master/lib/payload/exit-monitor.vala
So you must be dealing with an exit method not covered by it. (It's best-effort so it won't cover all possible cases, such as the process crashing.)

**Comment by bannsec** [comment]
Ah, yeah it's not catching a crash. Thanks!
