### ISSUE TITLE
a crash report on android(cased by bne.n instrument)

### ISSUE THREAD

**Issue by bigboysun** [frida/frida-gum#383]
I want hook a function,it‘s code is(12bytes head of function):

294e38:	6dc0      	ldr	r0, [r0, #92]	; 0x5c
294e3a:	2800      	cmp	r0, #0
294e3c:	bf18      	it	ne
294e3e:	f03b b88f 	bne.w	2cff60 
294e42:	4770      	bx	lr

It generated a trampoline (on_invoke_trampoline),  code is:
0xf3b3911c:	ldr	r0, [r0, #92]	; 0x5c
   0xf3b3911e:	cmp	r0, #0
   0xf3b39120:	it	ne
=> 0xf3b39122:	bne.n	0xf3b39126	; unpredictable <IT:ne>
   0xf3b39124:	b.n	0xf3b39130
   0xf3b39126:	push	{r0}
   0xf3b39128:	push	{r0}
   0xf3b3912a:	ldr	r0, [pc, #12]	; (0xf3b39138)
   0xf3b3912c:	str	r0, [sp, #4]
   0xf3b3912e:	pop	{r0, pc}

it crash at ==>,  crash report this “bne.n” is Illegal instrument

report：

signal 4 (SIGILL), code -6 (SI_TKILL), fault addr 0xdbc4e222 
I/AEE/AED (  484):     r0 c7c2d3f8  r1 00000010  r2 00000010  r3 ca50dab0
I/AEE/AED (  484):     r4 efe0d300  r5 000334b5  r6 000334b4  r7 ca50dad8
I/AEE/AED (  484):     r8 ca50daac  r9 00018f3c  sl d6c4226b  fp d6d40a71
I/AEE/AED (  484):     ip d59f6e39  sp ca50da68  lr dbc4e209  pc dbc4e222  cpsr a00f1830
I/AEE/AED (  484): 
I/AEE/AED (  484): backtrace:
I/AEE/AED (  484):     #00 pc 00000222  <unknown>
I/AEE/AED (  484):     #01 pc 00000205  <unknown>

**Comment by bigboysun** [comment]
b instrment with condition can't follow it instrument!!

**Comment by bigboysun** [comment]
will any body fix? or, i do

**Comment by oleavr** [comment]
Please submit a PR ❤️ This should be handled by ThumbRelocator in frida-gum.

**Comment by bigboysun** [comment]
This is an important patch. Many function headers will have IT instruction.

**Comment by oleavr** [comment]
@bigboysun Totally agree

**Comment by bigboysun** [comment]
I suggest adding a dynamic log to the “addlistener” function to print out the trampoline address, which can be opened by parameters, so that it is easy to diagnose the crash on the “trampoline”
as follows:

add listener:0xd6450a55 trapoline:0xefd6eee4 on_enter_trampoline:0xd99bed01 on_invoke_trampoline:0xd99bed1d on_leave_trampoline:0xd99bed09 code size:8 code:f0 b5 3 af 2d e9 0 7

**Comment by bigboysun** [comment]
The pr I submitted has a problem. The situation is far more complicated than expected. The jump of the IT instruction allows only one instruction, and the use of remote jump blocks is not allowed. It needs to be modified.

**Comment by bigboysun** [comment]
Two crash examples, see the attached file, the function signature is as follows

int test_itet(int inc, int numb);
int test_itt(int * x);
int test_itte(int x);

[test.S.zip](https://github.com/frida/frida-gum/files/3968094/test.S.zip)

**Comment by oleavr** [comment]
Thank you! Awesome work! :heart:
