### ISSUE TITLE
SEGFAULT when loading frida-gadget.so using LD_PRELOAD caused by lazy loading and the PLT/GOT.

### ISSUE THREAD

**Issue by jonwilson030981** [frida/frida-gum#391]
I hit a beast of an edge case this morning. But I'm not sure of the best approach to fix it. Again my setup is a little unusual, so I wouldn't be suprised if this is the root cause.

I am loading the gadget into my app at startup using LD_PRELOAD. Long story short, inside **gum_exceptor_backend_attach** in [gumexceptor-posix.c]( https://github.com/frida/frida-gum/blob/master/gum/backend-posix/gumexceptor-posix.c), frida replaces **_signal_** and **_sigaction_**. In my case the entries in the PLT/GOT had not yet been snapped by the loader (presumably nobody had called them yet). This resulted in frida actually hooking the little magic stub the loader uses to populate the PLT/GOT the first time a function is called thinking it was **_signal_**/**_sigaction_**. Unsuprisingly, things went very downhill from there resulting in a SEGFAULT that was pretty hard to diagnose. A simple workaround is to set the environment variable **LD_BIND_NOW=1**, but it would be good to find a fix, or at least add a means to detect things are about to go very wrong.

I though of using **_dlsym_** to find the symbols rather than just the names, or adding the **_-z,now_** linker option? Or perhaps just comparing signal and sigaction to see if they are the same (although this won't help if one of them is snapped and the other not).

**Comment by oleavr** [comment]
Thanks, nice catch! The solution we've used so far is `dlsym()`, so went for that.

**Comment by jonwilson030981** [comment]
Awesome! Thanks for the speedy fix.
