### ISSUE TITLE
Socket.connect  error Unable to create socket: Too many open files   after many times

### ISSUE THREAD

**Issue by 1215clf** [frida/frida-gum#403]
Hi, I've got a problem
The server is not enabled ,then the client tries to connect multiple times resulting in an error "Unable to create socket: Too many open files ", when I catch connect error ,  How to close it ?

**Comment by oleavr** [comment]
Thanks for reporting! This was fixed by the recent GLib upgrade. Stay tuned for the next release.

**Comment by oleavr** [comment]
Frida 12.9 is out with the fix.
