### ISSUE TITLE
vldr (arm thumb) instruction translation error

### ISSUE THREAD

**Issue by bigboysun** [frida/frida-gum#408]
My function header has "vldr" instruction. when i hook it, crashed! Function header as follow:

00ccd434 <xxxxxxx>:
ccd434: ed9f 1a1a   **vldr  s2, [pc, #104]**  
ccd438: ee00 1a10   vmov  s0, r1
ccd43c: ee20 2a01   vmul.f32  s4, s0, s2
ccd440: eebd 2ac2   vcvt.s32.f32  s4, s4

i checked coded, it don't translate vldr instruction,need fix

**Comment by bigboysun** [comment]
I fix? or you help?

**Comment by oleavr** [comment]
@bigboysun Nice catch! Would be great if you could fix it. I'm happy to assist if you have any questions 🙌
