### ISSUE TITLE
Gum fails to emit main executable in ModuleMap when alternative loader is used.

### ISSUE THREAD

**Issue by WorksButNotTested** [frida/frida-gum#414]
When an executable is loaded using the loader, e.g.:

/usr/arm-linux-gnueabi/lib/ld-2.27.so /bin/myapp

The when querying ModuleMap().values(), the executable /bin/myapp is omitted from the list of modules and the loader (ld-2.27.so) appears in the list twice. This appears to be because 
*gum_process_enumerate_modules_by_using_libc* is called by *gum_process_enumerate_modules*. This function uses the API *dl_iterate_phdr* to iterate through the shared libraries in the process, this is combined with the data in */proc/self/maps* to for the Module entry. This has the advantage over just presenting the raw */proc/pid/maps* data that it will not find false positives if an ELF is mapped as a flat file, and it may be more performant than opening each file in the maps to interrogate it.

As this API will omit the executable (it only deals with shared objects), this is then located by interrogating */proc/self/exe* to find the main executable and again collecting its information from the map. Since in this case */proc/self/exe* is  */usr/arm-linux-gnueabi/lib/ld-2.27.so* and not */bin/myapp*, and the loader has already been added to the ModuleMap through the *dl_iterate_phdr* mechanism, it appears twice. The executable itself, however, is absent.

**Comment by WorksButNotTested** [comment]
"""
Not immediately no, but perhaps we could check if there's an ELF that's not a shared library, and fall back to carving that out of /proc/self/maps as a last resort.
only drawback is that we have to do a lookahead to do that, as by convention the program itself should be first in the list
i.e. emitted first
(or well, not the only drawback... there's also the drawback of false positives, if the app just happens to have another program's executable mmap()ed somewhere in memory for some odd reason)
wonder if we could query the dynamic linker somehow
"""

**Comment by WorksButNotTested** [comment]
Here are a few things which I have considered:

1. Assume that argv[1] is the real executable if /proc/self/exe is a shared object rather than an executable. Won't work because PIE binaries are actually shared objects.
2. Use dlsym to find '_start' or 'main' and then dladdr to find the main module from there. This only works if the binary is compiled with '-rdynamic' as otherwise these symbols are only in .symtab and not .dynsym.
3. Add the compile flag '-Wl,--no-dynamic-linker' and '__attribute__((section(".interp")))
const char my_interp[] = "/usr/arm-linux-gnueabi/lib/ld-2.27.so"' to the source so that we can run the binary direct without needing to load using the loader. Means that our application cannot use the CRT and must declare _start rather than main. A useful workaround for making test executables, but no use when you need to use FRIDA on third party code which you can't control.
4. I should check if when working with a PIE executable (including when built with and without -rdynamic) whether this causes it to appear in the phdr iteration. If the duplicate entry bug only appears when running a loader as argv[0] then we may be able to use this as an indication. If so then we could try to find argv[1] in /proc/self/maps (this may require just to match on the basename since argv[1] may not be an absolute path and /proc/self/cwd may change (e.g. if chdir is called).
5. Maybe we just look for any stray executable mappings which look like ELF files at the end and put them on the end of the list. It isn't perfect, but may keep the code cleaner and be better than the module not being found at all and hence being unable to locate symbols within it. Technically, the loader is the main executable, (as shared libraries can be executed as long as they have an entry point).

**Comment by WorksButNotTested** [comment]
Current plan is:
1. Confirm that when running PIE executables, the executable doesn't appear in the phdr iteration.
2. Assuming this is the case (if not then back to the drawing board), when iterating the phdr, if the first entry is already in the emitted list then...
3. Processes the map looking for a partial name match on argv[1].
4. Add the new mapping in place of the duplicate.

**Comment by oleavr** [comment]
That sounds like a good plan :+1: 

(This is really mind-numbing :exploding_head:)

**Comment by WorksButNotTested** [comment]
Output from the following script when running a test executable both with and without the loader.

var map = new ModuleMap().values()
map.forEach(function(x)
{
    console.log('Name: ' + x.name + ', Base: ' + x.base);
});

$ ps axu | grep test
... /lib64/ld-linux-x86-64.so.2 ./test

$ sudo frida -p 3593 -l ./script.js 
                              
Name: libm-2.27.so, Base: 0x7f242e42c000
Name: frida-agent-64.so, Base: 0x7f242e7ca000
Name: librt-2.27.so, Base: 0x7f24340a6000
Name: libdl-2.27.so, Base: 0x7f24342ae000
Name: libresolv-2.27.so, Base: 0x7f24344b2000
Name: libpthread-2.27.so, Base: 0x7f2434ece000
Name: libc-2.27.so, Base: 0x7f24350ed000
Name: ld-2.27.so, Base: 0x7f24356e0000
Name: ld-2.27.so, Base: 0x7f24356e0000
Name: linux-vdso.so.1, Base: 0x7ffc78dee000

$ ps axu | grep test
... ./test

$ sudo frida -p 3675 -l ./script.js 
Name: test, Base: 0x558c5cc7e000
Name: frida-agent-64.so, Base: 0x7f9f2a7ca000
Name: libm-2.27.so, Base: 0x7f9f306ae000
Name: librt-2.27.so, Base: 0x7f9f30a4c000
Name: libdl-2.27.so, Base: 0x7f9f30c54000
Name: libresolv-2.27.so, Base: 0x7f9f30e58000
Name: libpthread-2.27.so, Base: 0x7f9f31874000
Name: libc-2.27.so, Base: 0x7f9f31a93000
Name: ld-2.27.so, Base: 0x7f9f31e84000
Name: linux-vdso.so.1, Base: 0x7ffe77bfa000

**Comment by WorksButNotTested** [comment]
Testing has also shown that the listing is correct when a test executable is run without the loader, but compiled with both -rdynamic and -fPIE -pie.

**Comment by WorksButNotTested** [comment]
The above test output shows the modules sorted in order of base address. This following script shows them in their original order.

var map = new ModuleMap(function(x)
{
    console.log('Name: ' + x.name + ', Base: ' + x.base);
});

**Comment by WorksButNotTested** [comment]
Summary of logic in *gum_emit_module_from_phdr* is when called back from 'dl_iterate_phdr', if it is the first time we are called back, then we check the path returned from the phdr against that in /proc/self/exe. If the paths do not match, then we lookup the path in '/proc/self/exe' in '/proc/self/maps' and emit a Module object if it is found there. The then emit the first entry from the phdr as normal. Subsequent entries from the phdr are just emitted one at a time.
