### ISSUE TITLE
Question: On error "only loaded scripts can be posted to"

### ISSUE THREAD

**Issue by Gbps** [frida/frida-gum#420]
Hi there.

I'm currently encountering an issue where I would like to block on a recv() call inside of my main JS script's body directly after a call to send(). I'm doing this to essentially create a JS -> Python RPC service.

The send() message is received by the message handler on the Python side, but it cannot post back a message due to the error `only loaded scripts can be posted to`. My assumption here is that the Python side has not marked the script as loaded yet because the JS script hasn't fully completed its body, as it is still blocking on `recv()`.

This has been resolved by me wrapping my entire JS script in a `setImmediate` call, but I am wondering if there's a better way to architect this so that all scripts which want to use my code do not need to wrap themselves in `setImmediate`. I am also wondering if there is already a solution for creating JS->Python "RPC" services.

Thanks!

**Comment by oleavr** [comment]
Hi,

Why not use the built-in [RPC](https://frida.re/docs/javascript-api/#rpc) API for this? It's built on top of `recv()` and `send()`.

Cheers!

**Comment by Gbps** [comment]
If I understand correctly, this API only works from Python->JS rather than the other way around. Maybe I'm reading the documentation wrong but I don't see a way for Python to expose an RPC back to JS.

**Comment by oleavr** [comment]
Ahh sorry, I misread your question. This is indeed not supported (at least yet). But I'm happy to accept a PR that allows posting messages to scripts in the `LOADING` state also.

**Comment by oleavr** [comment]
(It's generally a bad idea to do anything blocking in the script's load codepath though, as our API calls (except for RPC) have a timeout of 20 (or was it 25?) seconds. This is the default method call timeout of the underlying GDBus implementation that we use (for p2p DBus over our own platform-specific transport).

**Comment by Gbps** [comment]
Thanks for the reply :)

What are the concerns in the code that has lead to the prevention of sending messages in the LOADING state? If I were to submit a PR, what functionality would the agent need to provide that it currently doesn't while in LOADING?

Right now this is largely solved by wrapping the entire script in a setImmediate function. Is there a reason the script must remain blocking until it is entirely executed or would it make sense for scripts to be scheduled on the main js thread automatically as if setImmediate was called internally?

**Comment by oleavr** [comment]
> What are the concerns in the code that has lead to the prevention of sending messages in the LOADING state?

It didn't seem like a useful thing to support.

> Is there a reason the script must remain blocking until it is entirely executed or would it make sense for scripts to be scheduled on the main js thread automatically as if setImmediate was called internally?

It's very easy to create deadlocks and starve Frida's main loop, in turn causing other problems. I'm curious though why you didn't go for an asynchronous approach? (Using the callback passed to `recv()`, but without calling `wait()` on the result.) You could add that to a function that wraps that into a `Promise`, and using modern JavaScript you can use `async`/`await` to write synchronous-looking code. This is also possible with the Duktape runtime by using frida-compile. (See [frida-agent-example](https://github.com/oleavr/frida-agent-example) for boilerplate to get started.) Using `recv().wait()` is only recommended when you absolutely have to block the current thread, such as when needing to make a request to get some response inside `onEnter` or `onLeave`.

**Comment by Gbps** [comment]
The reason was to support the largest amount of scripts with the least amount of effort on the user and usable in the most number of places. By making it blocking, I didn't require that people who use my project (unreleased yet) to have to port their scripts to frida-compile to use, and also lets them use my apis within onEnter.

Currently there is a two-way communication passed back and forth from JS -> Python -> JS. The way it's implemented is by JS forming a request and a random token, Python receives the message, processes the request, then sends the result pack using the random token as the "type" value, so that the call to recv() gets the correct response.

The project also hooks into some of the default APIs to extend support, namely functions within DebugSymbol. Currently those functions block, so to support the same, my hook into those functions must also block.

**Comment by oleavr** [comment]
That makes sense. It's only a matter of changing [this](https://github.com/frida/frida-core/blob/3e4841dd7302441e2c3c898a7d47923937580db1/lib/payload/script-engine.vala#L435-L436). PR welcome :)

**Comment by Gbps** [comment]
Made a PR, adding a condition to allow LOADING scripts to be posted to worked as expected on my local build. The script no longer requires setImmediate to receive messages in its body. Thank you for the help!
