### ISSUE TITLE
Exceptor fails on android/32bit

### ISSUE THREAD

**Issue by trufae** [frida/frida-gum#422]
When reading 4 bytes from address 8 on android9/10 when attaching to a 32bit process (com.android.chrome or zygote) the process dies.

I did a workaround in r2frida because there was a bunch of people complaining on that, so i'm filling the issue here to point them here. and use the r2frida workaround until frida is ready.

**Comment by oleavr** [comment]
Thanks! Should be fixed as of 1168c64.
