### ISSUE TITLE
Compiling without C++11 support

### ISSUE THREAD

**Issue by lordneon** [frida/frida-gum#438]
Is it possible to compile gum without C++11 support?
I have an ancient version of gcc and I can't upgrade to a newer one.

Is there a particular feature of C++11 which gum uses throughout the code? 

Thanks.

**Comment by oleavr** [comment]
You could disable the V8 runtime by passing `v8=disabled` to Meson where we're invoking it when building Gum. However, what we've done on our CI to build Linux x86/x86_64 binaries that run on as many glibc versions as possible is that we have a CentOS 5 Docker image where we've added GCC 7.5 built from source. You can find the recipe here:
https://github.com/frida/frida-ci/tree/master/images/manylinux
