### ISSUE TITLE
Implement filedescriptor API

### ISSUE THREAD

**Issue by radare** [frida/frida-gum#51]
It would be nice if gum could provide an abstraction to manipulate filedescriptors, list them, dup, close, open, etc from the target process. This is what `dd` does in r2, and it can be retrieved on linux via /proc/pid/fd. on darwin probably with bruteforcing with fstat.

**Comment by oleavr** [comment]
Yes, this would be killer!

**Comment by oleavr** [comment]
This belongs in user-space modules in npm.

**Comment by radare** [comment]
Probably this issue should go in r2frida

**Comment by oleavr** [comment]
Yep would be neat to have this in r2frida.

**Comment by radare** [comment]
done in https://github.com/nowsecure/r2frida/issues/32 <https://github.com/nowsecure/r2frida/issues/32>

**Comment by oleavr** [comment]
Sweet! 👍
