### ISSUE TITLE
Android: frida-trace crashes at start on all apps

### ISSUE THREAD

**Issue by ant9000** [frida/frida-gum#518]
I've tested multiple apps and multiple version of the tools: I've not been able to hook any app except for zygote (not zygote64, which crashes).

Here is an example:

```
frida-trace -U -i gethostbyaddr_r org.mozilla.fennec_fdroid
Failed to start tracing: script is destroyed                            
Process crashed: Trace/BPT trap

***
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: '14.1-20201106-UNOFFICIAL-suzuran'
Build fingerprint: 'Sony/E5823/E5823:7.1.1/32.4.A.1.54/3761073091:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 8895, tid: 9064, name: gum-js-loop  >>> org.mozilla.fennec_fdroid <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
    x0   0000000000000000  x1   0000000000002368  x2   0000000000000006  x3   0000007ee52324c0
    x4   0000000000000040  x5   fefeff7de4226ee7  x6   fefeff7de4226ee7  x7   7f7f7f7fff7f7fff
    x8   00000000000000f0  x9   cf72139c891bb5c1  x10  ffffffffffffffff  x11  0000000000000000
    x12  0000007ee5231b64  x13  0000000000000000  x14  0000000000000000  x15  00291d01d4e9f329
    x16  0000007ee5231ce0  x17  0000007ee5231b9f  x18  00000000ffffffff  x19  0000000000000006
    x20  0000007ee52324c0  x21  0000000000002368  x22  000000000000003b  x23  0000007ee52374f8
    x24  0000007ee52324c0  x25  0000000000000000  x26  0000007f9d288018  x27  0000007f9d288028
    x28  0000000000000000  x29  0000007ee5232260  x30  0000007f9d29e1ec
    sp   0000007ee5232160  pc   0000007f9d2fd400  pstate 0000000000000000

backtrace:
    #00 pc 0000000000066400  /system/bin/linker64 (__dl_syscall+32)
    frida/frida#1 pc 00000000000071e8  /system/bin/linker64 (__dl__ZL24debuggerd_signal_handleriP7siginfoPv+1116)
    frida/frida#2 pc 0000000005860024  /data/app/org.mozilla.fennec_fdroid-1/lib/arm64/libxul.so (offset 0x2ed0000)
    frida/frida#3 pc 00000000001b1c30  /data/local/tmp/re.frida.server/frida-agent-64.so
***

```

All the other traces look similar. My device runs Android 7.1 on an aarch64 CPU. I've got Magisk installed, with magiskhide disabled.

Tested version of Frida are the following:

- frida 12.11.18 frida-tools 8.2.0 frida-server 12.11.18-android-arm64
- frida 14.0.8 frida-tools 9.0.0 frida-server 14.0.8-android-arm64
- frida 14.1.2 frida-tools 9.0.1 frida-server 14.1.2-android-arm64

Is there anything I could try for narrowing down the possible culprit?

Thanks a lot in advance.

**Comment by neomafo88** [comment]
> Thank you so much for digging into this!
> 
> This is a firmware-specific issue where we're failing to probe the Android dynamic linker's internals on your particular system. This is unfortunately not something we can fix without access to a device exactly like yours, so we will need your help to fix this one. The relevant code is [here](https://github.com/frida/frida-gum/blob/master/gum/backend-linux/gumandroid.c). I'd be happy to assist you in debugging this further if you'd be interested in taking a stab at fixing it. If so just reach out to me on Telegram (I'm `oleavr`), in our Telegram [group](https://t.me/fridadotre).

Wonder how you are able to tell from the stack trace in the crash log, that this was the root cause
> firmware-specific issue where we're failing to probe the Android dynamic linker's internals on your particular system
