### ISSUE TITLE
NativeCallback doesn't seem to work on Windows, except for mscdecl

### ISSUE THREAD

**Issue by taviso** [frida/frida-gum#525]
I can't seem to get `NativeCallback` to work on Windows/x86 with anything other than `mscdecl`. The stack is not being set up or cleared correctly for the other abis, but I'm not sure if I'm using it wrong, should these examples work?

(I'm just typing these into devtools, but I've tried using it from a script and also can't get it to work)

```javascript
var cb = new NativeCallback(function () { console.log("hello"); }, "void", [], "mscdecl");
var func = new NativeFunction(cb, "void", [], "mscdecl");
func() // This works
```

```javascript
var cb = new NativeCallback(function () { console.log("hello"); }, "void", [], "stdcall");
var func = new NativeFunction(cb, "void", [], "stdcall");
func() // Error: access violation
```

```javascript
var cb = new NativeCallback(function () { console.log("hello"); }, "void", [], "thiscall");
var func = new NativeFunction(cb, "void", [], "thiscall");
func() // Error: access violation
```

```javascript
var cb = new NativeCallback(function () { console.log("hello"); }, "void", [], "fastcall");
var func = new NativeFunction(cb, "void", [], "fastcall");
func() // Error: access violation
```

I think there's a documentation bug where it says "You may also specify the abi if not system default", but it seems to assume `mscdecl` which is not the system default on Windows, and doesn't match what `NativeFunction` assumes is the system default (stdcall).

**Comment by oleavr** [comment]
This is now finally fixed in Frida 14.2.3, and libffi patches have been submitted upstream 🎉 Thanks a lot for reporting and helping narrow this one down!
