### ISSUE TITLE
Where can I find those "devkit examples"?

### ISSUE THREAD

**Issue by CaledoniaProject** [frida/frida-gum#589]
On [this page](https://frida.re/docs/c-api/) it says "The example in the devkit shows you how to augment open and close from C only", but I couldn't find it in this repo.

Where can I find it?

**Comment by oleavr** [comment]
You can find the files they're generated from here:
https://github.com/frida/frida/tree/master/releng/devkit-assets

And compiled devkits here:
https://github.com/frida/frida/releases

**Comment by CaledoniaProject** [comment]
Thanks!
