### ISSUE TITLE
Frida doesn't works with ASAN

### ISSUE THREAD

**Issue by radare** [frida/frida-gum#6]
Looks like asan segfault handler is registered before the frida one, so the process dies before frida can handle it.

It will be interesting to have an API for managing the segfault exception in a better way, being able to call asan handler if desired.

**Comment by oleavr** [comment]
Great idea!

**Comment by oleavr** [comment]
This is now working but requires `export ASAN_OPTIONS=allow_user_segv_handler=true`.
