### ISSUE TITLE
How to represent an array in JavaScript when hooking Dalvik methods

### ISSUE THREAD

**Issue by GodricLiu** [frida/frida-gum#60]
Below is the Dalvik method I want to hook:
```
    public String hookMeArray(String args[])
    {
        return args[0] + args[1];
    }
```
Below is my hooking code:
```
Dalvik.perform(function () {
    var hook = Dalvik.use("com.example.godric.fridademo.Hook");
    hook.hookMeArray.overload("java.lang.String[]").implementation = function (s1) {
    //hook.hookMeArray.overload("[java.lang.String]").implementation = function (s1) {
    //hook.hookMeArray.overload("[java.lang.String").implementation = function (s1) {
    //The above three lines all meet a error
    //error messages : {u'lineNumber': 1259, u'type': u'error', u'description': u'Error: hookMeArray: specified argument types do not match any overload', u'fileName': u'gumscript-runtime-dalvik.js'} None
        send("Hook Array:");
        send(s1);
        var ret = hook.hookMeArray.overload("[java.lang.String").call(this, s1);
        send(ret);
        return ret;
    };
});
```
My question is how to represent the array in arguments? 
Many Thanks!

**Comment by oleavr** [comment]
Hi,

I don't think we handle this currently. If you feel like diving into the code and having a stab at implementing it, I would suggest copy-pasting the contents of “gumscript-runtime-dalvik.js” into a .js file that you load into a test app like this: `frida -R -l foo.js com.android.browser`, and just rename the one `ObjC` reference to something else and then add some test code at the bottom of the script that you use to test your changes. You may then edit the implementation and in the REPL just do `%reload` to try the new version quickly. Once you're happy with it just copy-paste it back into frida-gum, commit and submit a PR.

Cheers!

**Comment by oleavr** [comment]
The code is here: https://github.com/frida/frida-gum/blob/master/bindings/gumjs/gumscript-runtime-dalvik.js

**Comment by marc1006** [comment]
For String[] it works already.
Try
```
 hook.hookMeArray.overload("[Ljava.lang.String;").implementation = {...};
```

**Comment by oleavr** [comment]
Thanks @marc1006; assuming this is fixed.
