### ISSUE TITLE
ordering of exception handlers

### ISSUE THREAD

**Issue by d-millar** [frida/frida-gum#627]
Hi,

Am trying to use Process.setExceptionHandler without much success.  As a test example, am running the following in the Frida REPL:
     Process.setExceptionHandler(ex => { send('w00t'); });
     Memory.writeByteArray(ptr(0), [0xde, 0xad]);
I get the expected "access violation exception" but no "w00t".

This appears to be because gum_exceptor_handle_scope_exception and gum_quick_core_handle_crashed_js are added before my handler.  The latter pretty much always returns FALSE, but the former pretty much always returns TRUE.  (It returns FALSE for scope==NULL and scope->exception_occurred, but neither seem to be true generally.)   Given that gum_exceptor_add calls g_slist_append to add new handlers (vice g_slist_prepend), I'm not sure how I can ever get executed.  The queue will always short-circuit before my handler.

Any help appreciated,
D

**Comment by oleavr** [comment]
This is by design since `.writeByteArray()` throws a JS exception that you should handle. (The `Memory.{read/write}*()` APIs are deprecated by the way -- use the methods on `NativePointer` instead.)
