### ISSUE TITLE
Memory semantics of `Instruction`

### ISSUE THREAD

**Issue by miaouPlop** [frida/frida-gum#649]
Hi everyone,

When using the `Instruction` API (specifically the `Arm64Instruction`), I would like to access instruction semantics to change the behavior of the application using the `Stalker` when memory operations are conducted. I know that `Instruction.groups` can be used to do this but it does not give information about memory semantics: if memory (read or write) is used, what would be the address and length, etc.
If I understand it correctly, this information is available using Capstone (with `inst.mem`) but Frida does not make use of it. Is there another way to know if an instruction will use memory other than parsing `opStr` and looking for specific instruction mnemonics?

**Comment by oleavr** [comment]
Hey,

The proper solution here is to extend the `Instruction` API to expose what you need. (PR welcome!)

Cheers

**Comment by miaouPlop** [comment]
Okay, that's what I thought but I wanted to be sure before I dive in. 
Thank you, I'll try to do a PR in the coming weeks!
