### ISSUE TITLE
Problem with gum_darwin_fill_file_mapping on macOS Monterey on ARM64

### ISSUE THREAD

**Issue by stefan-esser-sg** [frida/frida-gum#668]
I ran into a problem with frida-mode in AFLplusplus on latest ARM64 macOS. After days of debugging I figured out that the problems were due to `gum_darwin_fill_file_mapping` not seeing that certain regions belong to a file. Therefore AFLplusplus thought they were JIT code. This happens e.g. when the frida interceptor code is patching said regions.
This is the function in question:

```
static gboolean
gum_darwin_fill_file_mapping (gint pid,
                              mach_vm_address_t address,
                              GumFileMapping * file,
                              struct proc_regionwithpathinfo * region)
{
  gint retval, len;

  retval = __proc_info (PROC_INFO_CALL_PIDINFO, pid, PROC_PIDREGIONPATHINFO,
      (uint64_t) address, region, sizeof (struct proc_regionwithpathinfo));

  if (retval == -1)
    return FALSE;

  len = strnlen (region->prp_vip.vip_path, MAXPATHLEN - 1);
  region->prp_vip.vip_path[len] = '\0';
```

I played around with this code and found that using `PROC_PIDREGIONPATHINFO2` instead of `PROC_PIDREGIONPATHINFO` seems to fix the issue. With `PROC_PIDREGIONPATHINFO2` even after modifications by interceptor the correct file mapping is still returned.

**Comment by oleavr** [comment]
Thanks for digging into this! ❤️ Nice catch 🙌

On vacation right now so can't investigate this just yet, but switching to `PROC_PIDREGIONPATHINFO2` sounds like it may be the way to go. We just need to ensure that it's available on the oldest XNU we support (and if not we'll need to pick the implementation at runtime).
