### ISSUE TITLE
illegal instruction on last Frida macOS m1

### ISSUE THREAD

**Issue by aviramha** [frida/frida-gum#698]
Running on macOS M1, when using Frida 16.0.7 sometimes we get illegal hardware instruction.
I couldn't investigate further but we will upload the macOS console log that appears for that crash sometimes.

**Comment by t4lz** [comment]
Here is the crash report, I changed the extension from .ips to .txt just so that GitHub lets me upload it: [node-2023-04-18-003036.txt](https://github.com/frida/frida-gum/files/11259544/node-2023-04-18-003036.txt)

**Comment by aviramha** [comment]
Happened between Frida 16.0.2 and 16.0.3

**Comment by aviramha** [comment]
Happens on 16.0.19.

**Comment by aviramha** [comment]
Introduced in commit 7d2b68f881a402913cf34cd5c24fa111bbef0bd0 in frida main repo.

**Comment by aviramha** [comment]
Commit details:

```


diff --git a/releng/deps.mk b/releng/deps.mk
index 3b89c51..fed3d34 100644
--- a/releng/deps.mk
+++ b/releng/deps.mk
@@ -1,4 +1,4 @@
-frida_deps_version = 20221111
+frida_deps_version = 20221021
 frida_bootstrap_version = 20220130
 
 
```
I think that `frida_deps_version` is what toolchain/sdk is used?
@oleavr

**Comment by aviramha** [comment]
reason is https://github.com/frida/frida-rust/issues/81
