### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x38 in tid 16884

### ISSUE THREAD

**Issue by 2361788963** [frida/frida-gum#774]
I am using frida-gum directly in my android project
I just  use
GumAddress address = gum_module_find_base_address("libart.so");
It cause an error. -> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x38 in tid 16884
Not only that, I used other gum_module_xxx function,and it report the same error  
-> Fatal signal 11 (SIGSEGV), code 1, fault addr 0x38 in tid 16884
I switched to the latest version and this is what happened too.
Why is this happening? It works fine with frida-service, but not with frida-gum in an Android project.

**Comment by 2361788963** [comment]
Sorry, it was my mistake, I didn't use gum_init_embedded () Initialize

**Comment by 2361788963** [comment]
But now I have a new problem, why I can get the symbols in the emulator at frida-service using Module.enumerateSymbols("libart.so").
Use gum_module_enumerate_symbols in frida-gum but can't get symbols.The real machine is fine, but not the simulator.

**Comment by s1341** [comment]
Does your binary contain symbols?

Closing anyway, as your original issue is resolved.
