### ISSUE TITLE
send/recv can't handle +Infinity, -Infinity and NaN

### ISSUE THREAD

**Issue by Tyilo** [frida/frida-gum#84]
This is mostly a problem for the python repl, as it'll display these value as `null`.

Python's `json` module already supports `+Infinity`, `-Infinity` and `NaN` out of the box, so I suggest that we use our own `JSON.stringify` and `JSON.parse` in `send` and `recv`.

For the parsing part we can use [JSON.parseMore](https://github.com/Canop/JSON.parseMore).

I haven't found anything for `JSON.stringify`, but we could implement that ourselves fairly easily.

**Comment by Tyilo** [comment]
Well I implemented it here: https://github.com/Tyilo/JSON_with_NaN

Should I add it to frida-gum?

**Comment by oleavr** [comment]
Let's leave this up to [user-space](https://www.npmjs.com/search?q=frida) modules.
