### ISSUE TITLE
Can't hook into constructor

### ISSUE THREAD

**Issue by marc1006** [frida/frida-gum#89]
``` javascript
this.hookConstructor = function () {
        Dalvik.perform(function() {
            klass = Dalvik.use('o.ᓙ');
            klass.$new.implementation = function(str, i) {
                const result = this.$new(str, i);
                return result;
            }
        });
    };
```

Results with a crash.

As far as I know it depends on the `this.$classHandle`. 
`env.getObjectRefType(this.$classHandle)` says it's a global reference. But when I'm trying to get the classname of it with `env.getClassName(this.$classHandle)` the app crashes with (+ dump)

```
E/dalvikvm(13974): JNI ERROR (app bug): attempt to use stale weak global reference 0x3
E/dalvikvm(13974): VM aborting
```

So `this.$classHandle` is actually no valid reference - but I don't know why.
### Update:

``` javascript
const Singleton = Dalvik.use("....Singleton");
Singleton.$new.overload("int").implementation = function (value) {
  return null;
  // return this.$new.overload("int")(value);
};
```

It works... But the value we get is completely wrong.

**Comment by pandasauce** [comment]
Ran into this same issue. Interestingly enough, depending on the way I hook it the results vary.

```$new.overloads[i]``` will crash the app.

```$new.overload()``` with ```apply(this, arguments)``` as the last line will freeze it with a black screen.

```$new.overload()``` with anything else will crash the app.

**Comment by su-vikas** [comment]
I encountered the same problem on Android 6.0.1, with Frida 8.1.13. When I try to attach to a constructor of a Java class, the application crashes.

**Comment by Piasy** [comment]
With Frida 10.0.10, Android 6.0.0, I can hook constructor with code below:

``` java
function print_args() {
    var str = "";
    for (var i = 0; i < arguments.length; i++) {
        str += arguments[i] + ", "
    }
    return str;
}

Java.perform(function () {
    var AudioRecord = Java.use("android.media.AudioRecord");

    AudioRecord.$init.overload("int", "int", "int", "int", "int").implementation = function (audioSource, sampleRateInHz, channelConfig, audioFormat, bufferSizeInBytes) {
        send("android.media.AudioRecord(" + this + ").<init>: " + print_args(audioSource, sampleRateInHz, channelConfig, audioFormat, bufferSizeInBytes));
        return this.$init(audioSource, sampleRateInHz, channelConfig, audioFormat, bufferSizeInBytes);
    };
});
```

If I use `$new`, it will give such error message: `Error: Reimplementing $new is not possible. Please replace implementation of $init instead.`, so I use `$init`, and it works.

**Comment by oleavr** [comment]
Thanks for pointing this out, @Piasy!
