### ISSUE TITLE
Dalvik Android 5 support

### ISSUE THREAD

**Issue by pandasauce** [frida/frida-gum#99]
Is support for Lollipop on the roadmap? What needs to be done to implement it?

```js
{u'lineNumber': 116, u'type': u'error', u'description': u'Error: Dalvik API not available', u'fileName': u'gumscript-runtime-dalvik.js'}
```

Emulator 5.1.1 armeabi-v7a

**Comment by oleavr** [comment]
It's supported in the latest code in git, where the ART integration gives you full API access and allows you to override methods. Enumerating classes and scanning memory for instances hasn't been ported yet though.

**Comment by pandasauce** [comment]
Wow, that was quick, thanks.

Should we keep the issue open then to tick it off once everything has been ported?

**Comment by oleavr** [comment]
Sounds good to me. I don't think I'll have time to add those features before the next release, though, so if you feel like hacking on either of them let me know and I'd be happy to assist.

**Comment by oleavr** [comment]
Let's keep tracking this in #105 and #106.
